### ISSUE TITLE
Hra se řádně neukončí

### ISSUE THREAD

**Issue by PavelMaca** [Koule7b/skoroAc-Man#2]
Dohraji hru tak že posbírám všechny body.
Hra ale jde dál.

Pokud pak narazím do duchů zobrazí se přes nápis "Vyhrál jsi..." nápis "Prohrál jsi..."
WTF??

**Comment by Koule7b** [comment]
Pokusi jsem se tim neco provest, snad uz b y to melo slapat, jak ma:-)
